# Generated by Django 5.1.1 on 2024-09-23 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GroupField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('is_description', models.BooleanField(default=False)),
                ('before_text', models.CharField(blank=True, max_length=32, null=True)),
                ('after_text', models.CharField(blank=True, max_length=32, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customfield_field', to='appproject.field')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customfield_group', to='appproject.groupfield')),
            ],
        ),
        migrations.CreateModel(
            name='CustomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=4000)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customfieldvalue_field', to='appproject.customfield')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customfieldvalue_item', to='appproject.item')),
            ],
        ),
    ]
