# Generated by Django 5.1.1 on 2024-09-24 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GroupField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('is_identifier', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customfield_field', to='appproject.field')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customfield_group', to='appproject.groupfield')),
            ],
        ),
        migrations.CreateModel(
            name='CustomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=4000, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customfieldvalue_field', to='appproject.customfield')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customfieldvalue_item', to='appproject.item')),
            ],
        ),
        migrations.CreateModel(
            name='FieldLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('text_before', models.CharField(blank=True, max_length=32, null=True)),
                ('text_after', models.CharField(blank=True, max_length=32, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldlink_fields', to='appproject.field')),
                ('subfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldlink_subfields', to='appproject.field')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('field', 'subfield'), name='unique_together_field_subfield')],
            },
        ),
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.UniqueConstraint(fields=('field', 'group'), name='unique_together_field_group'),
        ),
        migrations.AddConstraint(
            model_name='customservice',
            constraint=models.UniqueConstraint(fields=('item', 'field'), name='unique_together_item_field'),
        ),
    ]
