# Generated by Django 5.1.1 on 2024-09-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customfield',
            old_name='is_description',
            new_name='is_identifier',
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('field', 'group')},
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='after_text',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='before_text',
        ),
        migrations.CreateModel(
            name='FieldSelfRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('text_before', models.CharField(blank=True, max_length=32, null=True)),
                ('text_after', models.CharField(blank=True, max_length=32, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appproject.field')),
                ('subfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfields', to='appproject.field')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('field', 'subfield'), name='unique_field_subfield_relationship')],
            },
        ),
    ]
