# Generated by Django 5.1.1 on 2024-09-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0002_rename_customfield_fieldset_rename_groupfield_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldset',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='fieldset',
            name='is_identifier',
        ),
        migrations.RemoveField(
            model_name='fieldset',
            name='priority',
        ),
        migrations.AddField(
            model_name='obj',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obj',
            name='is_identifier',
            field=models.BooleanField(default=False),
        ),
    ]
