# Generated by Django 5.1.1 on 2024-09-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0002_rename_is_description_customfield_is_identifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customfield',
            old_name='is_required',
            new_name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='is_unique',
        ),
    ]
