# Generated by Django 5.1.1 on 2024-09-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0002_alter_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
