# Generated by Django 5.1.1 on 2024-09-29 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0003_alter_item_item_alter_rule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='template',
        ),
    ]
