# Generated by Django 5.1.1 on 2024-09-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0003_remove_fieldset_is_hidden_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FieldSet',
            new_name='GroupSet',
        ),
        migrations.AddField(
            model_name='field',
            name='template',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='template',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='template',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
