# Generated by Django 5.1.1 on 2024-09-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0003_rename_is_required_customfield_is_hidden_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fieldselfrelationship',
            name='unique_field_subfield_relationship',
        ),
    ]
