# Generated by Django 5.1.1 on 2024-09-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0004_remove_fieldselfrelationship_unique_field_subfield_relationship'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fieldselfrelationship',
            constraint=models.UniqueConstraint(fields=('field', 'subfield'), name='unique_field_subfield'),
        ),
    ]
